require 'phonetic/nysiis'
require 'phonetic/soundex'
require 'phonetic/refined_soundex'
require 'phonetic/metaphone'
require 'phonetic/double_metaphone'
require 'phonetic/metaphone2'
require 'phonetic/caverphone2'
require 'phonetic/core_ext/string'
