module Phonetic
  NYSIIS_TEST_TABLE = {
    'acknowledge'   => 'ACNALADG',
    'Alexandra'     => 'ALAXANDR',
    'Alphonso'      => 'ALFANS',
    'Aumont'        => 'AANAD',
    'Bonnie'        => 'BANY',
    'Christensen'   => 'CHRASTANSAN',
    'Cleveland'     => 'CLAFALAD',
    'Claudia'       => 'CLAD',
    'Dedee'         => 'DADY',
    'DeLaurentiis'  => 'DALARANT',
    'Echikunwoke'   => 'ECACANWAC',
    'Fahey'         => 'FAHY',
    'Jacqueline'    => 'JACGALAN',
    'John'          => 'J',
    'Hessel'        => 'HASAL',
    'Hubert'        => 'HABAD',
    'Howard'        => 'HAD',
    'Knuth'         => 'NNAT',
    'Kepler'        => 'CAPLAR',
    'Marguerite'    => 'MARGARAT',
    'Macdonald'     => 'MCDANALD',
    'Michael'       => 'MACAL',
    'Phoenix'       => 'FFANAX',
    'pizza'         => 'PAS',
    'Pfeiffer'      => 'FFAFAR',
    'Rebecca'       => 'RABAC',
    'Rosalind'      => 'RASALAD',
    'Schmidt'       => 'SSNAD',
    'Schelte'       => 'SSALT',
    'Smith'         => 'SNAT',
    'weschsler'     => 'WASLAR'
  }
end
